### ISSUE TITLE
文件名去掉timestamp

### ISSUE THREAD

**Issue by yoloyyh** [Hackerl/zero#3]
https://github.com/Hackerl/zero/blob/24b5dd4c67abff7ba908af40131d3413ac624d16/src/log.cpp#L61

**Comment by Hackerl** [comment]
因为要支持 `rotate`，使用时间戳可以快速按时间排序，并可以区分不同时间段的日志文件。
如果需要去掉，可以考虑自定义 `provider`，添加到全局 `logger` 中。
